[package]
name = "rust_t"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
rand = "0.8.5"
number_prefix = "0.4.0"
plotters = "0.3.0"
rand_distr = "0.4.3"
statrs = "0.14.0"
